"""
OmniSight-AI Behavioral Feature Engineering Package.
Provides pure mathematical feature extraction and database persistence services.
"""

from src.features.extractor import (
    extract_behavioral_features,
    FEATURE_NAMES,
    FEATURE_ATTEMPT_DURATION_SEC,
    FEATURE_ABSENCE_EVENT_COUNT,
    FEATURE_ABSENCE_TOTAL_DURATION_SEC,
    FEATURE_ABSENCE_MAX_DURATION_SEC,
    FEATURE_ABSENCE_AVG_DURATION_SEC,
    FEATURE_ABSENCE_TIME_RATIO,
    FEATURE_MULTI_FACE_EVENT_COUNT,
    FEATURE_MULTI_FACE_TOTAL_DURATION_SEC,
    FEATURE_MULTI_FACE_MAX_DURATION_SEC,
    FEATURE_MULTI_FACE_TIME_RATIO,
    FEATURE_TOTAL_MONITORING_EVENTS,
    FEATURE_EVENT_RATE_PER_MINUTE,
    FEATURE_EARLY_EXAM_EVENT_RATIO,
    FEATURE_MID_EXAM_EVENT_RATIO,
    FEATURE_LATE_EXAM_EVENT_RATIO,
    FEATURE_AVG_INTER_EVENT_INTERVAL_SEC,
    FEATURE_QUESTIONS_ANSWERED_RATIO,
    FEATURE_ATTEMPT_DURATION_PER_ANSWERED_QUESTION_SEC,
)
from src.features.service import (
    extract_and_persist_behavioral_features,
    get_behavioral_feature_vector,
    get_feature_matrix,
)

__all__ = [
    "extract_behavioral_features",
    "extract_and_persist_behavioral_features",
    "get_behavioral_feature_vector",
    "get_feature_matrix",
    "FEATURE_NAMES",
    "FEATURE_ATTEMPT_DURATION_SEC",
    "FEATURE_ABSENCE_EVENT_COUNT",
    "FEATURE_ABSENCE_TOTAL_DURATION_SEC",
    "FEATURE_ABSENCE_MAX_DURATION_SEC",
    "FEATURE_ABSENCE_AVG_DURATION_SEC",
    "FEATURE_ABSENCE_TIME_RATIO",
    "FEATURE_MULTI_FACE_EVENT_COUNT",
    "FEATURE_MULTI_FACE_TOTAL_DURATION_SEC",
    "FEATURE_MULTI_FACE_MAX_DURATION_SEC",
    "FEATURE_MULTI_FACE_TIME_RATIO",
    "FEATURE_TOTAL_MONITORING_EVENTS",
    "FEATURE_EVENT_RATE_PER_MINUTE",
    "FEATURE_EARLY_EXAM_EVENT_RATIO",
    "FEATURE_MID_EXAM_EVENT_RATIO",
    "FEATURE_LATE_EXAM_EVENT_RATIO",
    "FEATURE_AVG_INTER_EVENT_INTERVAL_SEC",
    "FEATURE_QUESTIONS_ANSWERED_RATIO",
    "FEATURE_ATTEMPT_DURATION_PER_ANSWERED_QUESTION_SEC",
]
